name: SonarCloud Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Instalar herramientas de compilación para C++
      - name: Install build tools
        run: sudo apt-get install build-essential

      # Compilar usando el Build Wrapper
      - name: Build with Build Wrapper
        run: |
          build-wrapper-linux-x86-64 --out-dir bw-output make clean all

      # Ejecutar análisis de SonarCloud
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.9
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=mi-organizacion
            -Dsonar.projectKey=mi-proyecto
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.cfamily.build-wrapper-output=bw-output

